export const cropOptions = [
  { value: "ocean1", label: "Achilea" },
  { value: "blue", label: "Alstoemeria" },
  { value: "purple", label: "Asters" },
  { value: "red", label: "Astrantia" },
  { value: "orange", label: "Carnations" },
  { value: "yellow", label: "Chrysanthemum" },
  { value: "green", label: "Delphinium" },
  { value: "forest", label: "Eryngium" },
  { value: "slate", label: "Gypsophila" },
  { value: "silver", label: "Hydrangea" },
  { value: "silver", label: "Hypericum" },
  { value: "silver", label: "Lepidium" },
  { value: "silver", label: "Lily" },
  { value: "silver", label: "Limonium" },
  { value: "silver", label: "Mathiola" },
  { value: "silver", label: "Onis" },
  { value: "silver", label: "Phlox" },
  { value: "silver", label: "Roses" },
  { value: "silver", label: "Snapdragon" },
  { value: "silver", label: "Solidago" },
  { value: "silver", label: "Stokisia" },
  { value: "silver", label: "Sunflowers" },
  { value: "silver", label: "Veronica" }
];

export const productMizani =  [
  {value: "inicial", label: "Chrysal Inicial "},
  {value: "inicial", label: "Chrysal RVBc "},
  {value: "inicial", label: "RVBc + AVB "},
  {value: "inicial", label: "Chrysal AVB + RVBc + Optigyp "},
  {value: "inicial", label: "Chrysal AVB + RVB + Sugar "},
  {value: "inicial", label: "Chrysal Professional 2 "},
  {value: "inicial", label: "Chrysal AVB + AVB Booster "},
  {value: "inicial", label: "Re-used RVBc "},
  {value: "inicial", label: "TOG-6 + Aluminium Sulphate "},
  {value: "inicial", label: "TOG-6 "},
  {value: "inicial", label: "TOG-6 + Citric Acid "},
  {value: "inicial", label: "Gallileo "},
  {value: "inicial", label: "TOG-30 "},
  {value: "inicial", label: "Vaselife Hydrating treatment "},
  {value: "inicial", label: "Recycle Vaselife Hydrating treatment "},
  {value: "inicial", label: "Reused Vaselife Hydrating treatment "},
  {value: "inicial", label: "H100 powder "},
  {value: "inicial", label: "H100 liquid "},
  {value: "inicial", label: "H100 ultra clear solution "},
  {value: "inicial", label: "Aluminium Sulphate + Calcium Hypochlorite "},
  {value: "inicial", label: "STS 75 + TOG3 + normal sugar "},
  {value: "inicial", label: "Plain water "},
  {value: "inicial", label: "Jik "},
  {value: "inicial", label: "None "},
  {value: "inicial", label: "None - Grade & pack "},
  {value: "inicial", label: "Florissant 210 "},
  {value: "inicial", label: "Florissant 100 "},
  {value: "inicial", label: "STS 75 + TOG3 + Optigyp "},
  {value: "inicial", label: "Chrysal SVB "},
  {value: "inicial", label: "Chrysal SVB + AVB "},
  {value: "inicial", label: "Chrysal AVB "},
  {value: "inicial", label: "Chrysal AVB + BVB "},
  {value: "inicial", label: "Chrysal BVB "},
  {value: "inicial", label: "Florissant 210 + 100 "},
  {value: "inicial", label: "Reused Chrysal Inicial "},
  {value: "inicial", label: "Recycled Chrysal Inicial "},
  {value: "inicial", label: "Reused AVB + Optigyp "},
  {value: "inicial", label: "Reused Florissant 210 + 100 "},
  {value: "inicial", label: "Reused STS 75 + TOG3 + Optigyp "},
  {value: "inicial", label: "Reused Chrysal AVB + RVBc + Optigyp "},
  {value: "inicial", label: "Reused Chrysal AVB + RVBc + sugar "},
  {value: "inicial", label: "Reused STS 75 + TOG3 + sugar "},
  {value: "inicial", label: "Reused TOG6 "},
  {value: "inicial", label: "Reused AVB solution "},
  {value: "inicial", label: "Recycled Chrysal RVB clear "},
  {value: "inicial", label: "Chrysal AVB + Booster "},
  {value: "inicial", label: "Reused Chrysal AVB + Booster "},
  {value: "inicial", label: "Chrysal AVB + SVB "},
  {value: "inicial", label: "Chrysal SVB + RVBc "},
  {value: "inicial", label: "Re used Chrysal SVB + RVBc "},
  {value: "inicial", label: "Re used Chrysal SVB + AVB "},
  {value: "inicial", label: "AVB + RVBc "},
  {value: "inicial", label: "Re used AVB + RVBc "},
  {value: "inicial", label: "TOG 101 "},
  {value: "inicial", label: "Express 100 "},
  {value: "inicial", label: "Vase life UNO "}
];

